### ISSUE TITLE
WARNING for package users: Major column error bug

### ISSUE THREAD

**Issue by prateekt** [jamesware/denovolyzeR#12] opened 2016-07-28 17:42 UTC
The release when you download in R

install.packages("denovolyzeR")

(http://denovolyzer.org/) has a major bug with the column headers. It is a scientific hazard for naive users of the packages.

First of all, despite the fact that gene name is column 1, the column headers never spit out that column name. The column headers are always shifted by 1.

But the second bug is much more dangerous, and seriously needs to be fixed. When you use includeClasses=c("non","splice","syn","lof","mis") option for denovolyzeByGene (and possibly for other protocols), the column orders do NOT come out in the specified format for the data, even though the column headers are labeled as much. 

The data columns come out in the order that are empirically encountered in the input data from top to bottom of the input file. For instance, if "syn" is encountered first, the first three columns will actually be "syn" even though in this example, the user thinks they are getting "non" columns. They will be deceptively labeled as "non," even though are actually "syn".

Moral of the story: You better check your counts to make sure the empirical counts match up with the mutation type p value. If you're not careful with this package, you could accidentally think there is an enrichment of "mis" mutations when it's actually "syn" or so forth.

**Comment by jamesware** [comment] 2016-07-29 10:38
Thank you very much for taking the time to flag this up - I am very grateful for the feedback.

In response to the first issue, the `denovolyzeByGene` function outputs a data.frame, with gene names as row.names.  They are not in a column.  I am therefore not able to reproduce your error: the column names for me are correctly aligned with their contents, but I can see that it could be confusing if you interpreted the gene names as an unlabelled column.  I will consider moving the genes from row names to a column (but this would not be backwards compatible).

I _am_ able to reproduce the second issue that arises when you over-ride the default `includeClasses` assignment.  This may have arisen in the new release (triggered by changes in the dplyr package), and needs fixing.

Many thanks indeed for the feedback.

**Comment by prateekt** [comment] 2016-07-29 15:41
Cool thanks for getting back! Sorry if I was a bit harsh. The package overall is very useful, and a great contribution to the genomics community.

With respect to the first issue, I used R's write.table. You're right -- technically in R, that is not a column so when it is written, the column header won't be there (though the column will still be written). It would be nice to make it so that when someone uses write.table on the data frame, it writes the "geneName" column header name as the first cell since write.table after computation of the protocol results is a common use case with the package. Though, fine if it is more of a feature enhancement request.

With respect to the second issue, here is the synthetic test case I used to figure out what was going on:

--denovolyzeR_test.txt--
Gene    Class
GIGYF1  non
GIGYF1  splice
GIGYF1  splice
GIGYF1  syn
GIGYF1  syn
GIGYF1  syn
GIGYF1  mis
GIGYF1  mis
GIGYF1  mis
GIGYF1  mis

There are 1 non, 2 splice, 3 syn, 4 mis. So one can track the expected counts in the column and figure out what the ordering is.

**Comment by jamesware** [comment] 2016-07-29 16:30
I think this is now fixed.

I have not had an opportunity to test fully, and have not pushed updates to CRAN, but if you want to use the patched version you could install from github using devtools, and I hope that my revisions have not introduced any new glitches.

I have also switched the gene names from row names to a column.
If you encounter a similar situation elsewhere, you may find it helpful to note that `write.table` does has a solution for this:

> By default there is no column name for a column of row names. If col.names = NA and row.names = TRUE a blank column name is added, which is the convention used for CSV files to be read by spreadsheets.
- note that the multiHits function still has variant classes as row names, as I have not had time to change this

Thanks again for taking the time to flag this up.

**Comment by jamesware** [comment] 2016-08-01 13:03
The patch has now been tested and deployed to CRAN in release 0.2.0

**Closed as completed by jamesware** 2016-08-01 13:03 UTC
